### ISSUE TITLE
istio-proxy could be added twice in `ContainerResourceRequests`

### ISSUE THREAD

**Issue by sanposhiho** [mercari/tortoise#355]
istio-proxy could be added twice in `ContainerResourceRequests` if the deployment has the sidecar injection annotation and it's using the custom injection:
https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#customizing-injection

```
...
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
        sidecar.istio.io/proxyCPU: 502m
    spec:
      containers:
      - name: istio-proxy # https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#customizing-injection
        resources:
          requests:
            cpu: 501m
            memory: 129Mb
```
