### ISSUE TITLE
better support for pubsub / batch workers

### ISSUE THREAD

**Issue by sanposhiho** [mercari/tortoise#391]
pubsub/batch workers don't receive the traffic always. They're busy sometimes and free for other periods.
Given Tortoise generates the recommendation based on VPA's recommendation and VPA takes a recent usage with more weight, it can suggest something inappropriate for those workers.
For now, the only way is to define `minAllocatedResource` in those tortoises so that tortoise doesn't scale down very much.

This issue is to make Tortoise generate better recommendation for them too.
- [ ] https://github.com/mercari/tortoise/issues/293

**Comment by fatihtekin** [comment]
I am very new to the source code but I really like how and what you solve with Tortoise. So I would like to approach if it makes sense to use a configuration in the Tortoise.

Example CR:
```
apiVersion: tortoise.mercari.com/v1alpha1
kind: Recommendation
metadata:
  name: batch-worker-recommendation
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: batch-worker
  scalingStrategy:
    type: burstAware
    minCPU: 250m
    minMemory: 512Mi
    smoothingWindow: 10m

```
Fields:
- burstAware: tells Tortoise to adjust recommendation logic. 
- minCPU / minMemory: ensures pods aren’t undersized.
- smoothingWindow: average CPU/memory over last X minutes instead of all history → reduces idle drag.


Ideally what we care is how much Tortoise will influence for the time of the active traffic. For HPA Keda handles that by checking the `lagThreshold` however it wont influence the VPA. So one idea would be to watch a KEDA which is configured passive (`autoscaling.keda.sh/paused: "true"`) and using the records created to decide on the scale up/down.

I hope to hear your thoughts on these suggestions.
